services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd12345
    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  sql_server_data: