DECLARE @MESSAGE NVARCHAR(MAX) = '', 
        @TEACHER_EMAIL_LIST_XML XML = '',
        @STUDENT_EMAIL_LIST NVARCHAR(MAX) = '',
        @COUNT_OF_TEACHER INT = 0;

BEGIN TRY
  BEGIN TRANSACTION;

  SET @TEACHER_EMAIL_LIST_XML = @teacher_email_xml;

  -- PART 1: GET STRING VALUE OF STUDENT EMAIL LIST FROM COMMONSTUDENTS
  --         BASED ON TEACHER EMAIL LIST
  ;WITH TEACHER_EMAIL_LIST AS (
    SELECT email.value('.', 'NVARCHAR(100)') AS [TEACHER_EMAIL]
    FROM @TEACHER_EMAIL_LIST_XML.nodes('/teachers/email') AS T(email)
  )
  SELECT 
    @STUDENT_EMAIL_LIST += [studentEmailList] + ',' ,
    @COUNT_OF_TEACHER += 1
  FROM 
	  CommonStudents
  WHERE 
    [teacherEmail] IN (
      SELECT [TEACHER_EMAIL] 
      FROM TEACHER_EMAIL_LIST
    );

  -- PART 2: SELECT DISTINCT STUDENT EMAIL FROM 
  --         THE STRING VALUE OF STUDENT EMAIL LIST
  SELECT DISTINCT
    [value] AS [students]
  FROM
    string_split(
    LEFT(@STUDENT_EMAIL_LIST, (LEN(@STUDENT_EMAIL_LIST)-1) ),
    ',')
  GROUP BY 
    [value]
  HAVING 
    COUNT([value]) = @COUNT_OF_TEACHER


  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  ROLLBACK TRANSACTION
  SET @MESSAGE = 'AN ERROR OCCURRED: ' + ERROR_MESSAGE();
END CATCH

SELECT @MESSAGE AS [message];

